version: '3'

services:
  mock-service:
    build: ./test/mock_target
    command: bash -c "yarn && yarn mock"
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'grpc_health_probe -addr localhost:8443 -service helloworld.Greeter || exit 1',
        ]
      interval: 5s
      timeout: 1s
      start_period: 60s
    ports:
      - '8443:8443'
    volumes:
      - .:/src
    working_dir: /src

  test-runner:
    image: node:12
    command: yarn test
    depends_on:
      mock-service:
        condition: service_healthy
    environment:
      GRPC_HOST: mock-service:8443
    volumes:
      - .:/src
    working_dir: /src
