name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn ci
      - run: yarn rollup -c
      - run: yarn lint
      - run: docker-compose up --exit-code-from test-runner
