name: Publish

on:
  release:
    types: [created]
  push:
    branches:
      - rollup

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait on build
        uses: lewagon/wait-on-check-action@master
        with:
          check-name: 'build'
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

  publish-npm:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: check-package-version
        id: check-package-version
        uses: geritol/match-tag-to-package-version@0.1.0
        env:
          TAG_PREFIX: refs/tags/v
      - run: yarn ci
      - run: yarn rollup -c
      - run: npm publish --dry-run
      #- run: yarn publish --non-interactive
      # env:
      #   NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   PACKAGE_VERSION: ${{ steps.check-package-version.outputs.PACKAGE_VERSION }}
